version: "3.8"

services: 

  nginx:
    image: hoang12345/eztest-nginx
    ports: 
      - '8000:80'
    volumes: 
      - ./backend:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - backend
      - mysql
  
  backend:
    image: hoang12345/eztest-backend
    volumes: 
      - ./backend:/var/www/html:delegated

  frontend:
    image: hoang12345/eztest-frontend
    working_dir: /usr/src/app
    volumes: 
      - ./frontend/:/usr/src/app 
    ports: 
      - '4200:80'

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
      SERVICE_NAME: mysql
  
