import { CoreMenu } from '@core/types';
import { AppConfig } from 'app/app-config';

export const menu: CoreMenu[] = [
  {
    id: 'home',
    title: 'Home',
    translate: 'Home',
    type: 'item',
    icon: 'home',
    url: 'home',
  },
  {
    id: 'registration',
    title: 'Registration',
    translate: 'Registration',
    type: 'item',
    icon: 'user-plus',
    url: 'registration',
    permissions: [AppConfig.PERMISSIONS.registration],
  },
  {
    id: 'admin-registration',
    title: 'Admin Registration',
    translate: 'Admin Registration',
    type: 'item',
    icon: 'user-check',
    url: 'admin-registration',
    permissions: [AppConfig.PERMISSIONS.manage_registrations],
  },
  {
    id: 'teams',
    title: 'Teams',
    translate: 'Teams',
    type: 'collapsible',
    icon: 'users',
    children: [
      {
        id: 'team_management',
        title: 'Team Management',
        translate: 'Team Management',
        type: 'item',
        icon: 'circle',
        url: 'teams/team-management',
        permissions: [AppConfig.PERMISSIONS.team_management],
      },
      {
        id: 'team_assignment',
        title: 'Team Assinment',
        translate: 'Team Assignment',
        type: 'item',
        icon: 'circle',
        url: 'teams/team-assignment',
        permissions: [
          AppConfig.PERMISSIONS.assign_players ||
            AppConfig.PERMISSIONS.assign_coaches,
        ],
      },
      {
        id: 'teams',
        title: 'Teamsheets',
        translate: 'Teamsheets',
        type: 'item',
        icon: 'circle',
        url: 'teams/teamsheets',
        permissions: [AppConfig.PERMISSIONS.manage_teamsheets],
      },
    ],
  },
  {
    id: 'Leagues',
    title: 'Leagues',
    translate: 'Leagues',
    type: 'collapsible',
    icon: 'award',
    children: [
      {
        id: 'manage_leagues',
        title: 'League',
        translate: 'Manage Leagues',
        type: 'item',
        icon: 'circle',
        url: 'leagues/manage',
        permissions: [AppConfig.PERMISSIONS.manage_leagues],
      },
      {
        id: 'league_matches',
        title: 'Matches',
        translate: 'Matches',
        type: 'item',
        icon: 'circle',
        url: 'leagues/matches',
        permissions: [AppConfig.PERMISSIONS.update_score],
      },
      {
        id: 'league_report',
        title: 'Matches Report',
        translate: 'Matches Report',
        type: 'item',
        icon: 'circle',
        url: 'leagues/reports',
        permissions: [AppConfig.PERMISSIONS.league_reports],
      },
    ],
  },
  {
    id: 'fixtures-results',
    title: 'Fixtures & Results',
    translate: 'Fixtures & Results',
    type: 'item',
    icon: 'calendar',
    url: 'leagues/fixtures-results',
  },
  {
    id: 'streaming',
    title: 'Streaming',
    translate: 'Streaming',
    type: 'item',
    icon: 'video',
    url: 'streaming',
  },
  {
    id: 'messages',
    title: 'Messages',
    translate: 'Messages',
    type: 'item',
    icon: 'message-square',
    url: 'messages',
    permissions: [AppConfig.PERMISSIONS.send_messages],
  },
  {
    id: 'tables',
    title: 'Tables',
    translate: 'Tables',
    type: 'collapsible',
    icon: 'grid',
    children: [
      {
        id: 'Events',
        title: 'Events',
        translate: 'Events',
        type: 'item',
        icon: 'circle',
        url: 'tables/events',
        permissions: [AppConfig.PERMISSIONS.manage_events],
      },
      {
        id: 'Clubs',
        title: 'Clubs',
        translate: 'Clubs',
        type: 'item',
        icon: 'circle',
        url: 'tables/clubs',
        permissions: [AppConfig.PERMISSIONS.manage_clubs],
      },
      {
        id: 'Locations',
        title: 'Locations',
        translate: 'Locations',
        type: 'item',
        icon: 'circle',
        url: 'tables/locations',
        permissions: [AppConfig.PERMISSIONS.manage_locations],
      },
      {
        id: 'Users',
        title: 'Users',
        translate: 'Users',
        type: 'item',
        icon: 'circle',
        url: 'tables/users',
        permissions: [AppConfig.PERMISSIONS.manage_users],
      },
    ],
  },
  {
    id: 'settings',
    title: 'Settings',
    translate: 'Settings',
    type: 'item',
    icon: 'settings',
    url: 'settings',
    role: [AppConfig.USER_ROLES.admin],
  },
  {
    id: 'check-update',
    title: 'Check for update',
    translate: 'Check for update',
    type: 'item',
    icon: 'refresh-ccw',
    url: 'check-update',
  },
  {
    id: 'releases',
    title: 'Releases',
    translate: 'Releases',
    type: 'item',
    icon: 'package',
    url: 'releases',
    role: [AppConfig.USER_ROLES.admin],
  },
];
