<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class StageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('stages')->truncate();
        $env = env('APP_ENV');
        $created_at = now();
        $updated_at = now();

        if ($env === 'development') {
            $stages = [
                ['id' => 1, 'name' => 'League', 'type' => 'League', 'tournament_id' => 1, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Total', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 2, 'name' => 'League', 'type' => 'League', 'tournament_id' => 2, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Total', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 3, 'name' => 'League', 'type' => 'League', 'tournament_id' => 3, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Total', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 4, 'name' => 'League', 'type' => 'League', 'tournament_id' => 4, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Total', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 7, 'name' => 'League', 'type' => 'League', 'tournament_id' => 7, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 10, 'name' => 'League', 'type' => 'League', 'tournament_id' => 10, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 17, 'name' => 'League', 'type' => 'League', 'tournament_id' => 17, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 23, 'name' => 'League', 'type' => 'League', 'tournament_id' => 23, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 24, 'name' => 'League', 'type' => 'League', 'tournament_id' => 24, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Total', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 25, 'name' => 'League', 'type' => 'League', 'tournament_id' => 25, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 26, 'name' => 'League', 'type' => 'League', 'tournament_id' => 26, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 29, 'name' => 'League', 'type' => 'League', 'tournament_id' => 29, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Total', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 32, 'name' => 'League', 'type' => 'League', 'tournament_id' => 32, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 33, 'name' => 'League', 'type' => 'League', 'tournament_id' => 33, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 34, 'name' => 'League', 'type' => 'League', 'tournament_id' => 34, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 35, 'name' => 'League', 'type' => 'League', 'tournament_id' => 35, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 37, 'name' => 'League', 'type' => 'League', 'tournament_id' => 37, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 38, 'name' => 'League', 'type' => 'League', 'tournament_id' => 38, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 39, 'name' => 'League', 'type' => 'League', 'tournament_id' => 39, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 40, 'name' => 'League', 'type' => 'League', 'tournament_id' => 40, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 41, 'name' => 'League', 'type' => 'League', 'tournament_id' => 41, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 42, 'name' => 'League', 'type' => 'League', 'tournament_id' => 42, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 43, 'name' => 'League', 'type' => 'League', 'tournament_id' => 43, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 44, 'name' => 'League', 'type' => 'League', 'tournament_id' => 44, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 46, 'name' => 'League', 'type' => 'League', 'tournament_id' => 46, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 47, 'name' => 'League', 'type' => 'League', 'tournament_id' => 47, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 48, 'name' => 'League', 'type' => 'League', 'tournament_id' => 48, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 49, 'name' => 'League', 'type' => 'League', 'tournament_id' => 49, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 53, 'name' => 'League', 'type' => 'League', 'tournament_id' => 53, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 54, 'name' => 'League', 'type' => 'League', 'tournament_id' => 54, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 55, 'name' => 'League', 'type' => 'League', 'tournament_id' => 55, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 56, 'name' => 'League', 'type' => 'League', 'tournament_id' => 56, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 57, 'name' => 'League', 'type' => 'League', 'tournament_id' => 57, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 71, 'name' => 'League', 'type' => 'League', 'tournament_id' => 71, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Total', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 75, 'name' => 'Groups', 'type' => 'Groups', 'tournament_id' => 75, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 175, 'name' => 'Knockout', 'type' => 'Knockout', 'tournament_id' => 75, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 76, 'name' => 'Groups', 'type' => 'Groups', 'tournament_id' => 76, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 176, 'name' => 'Knockout', 'type' => 'Knockout', 'tournament_id' => 76, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 77, 'name' => 'Groups', 'type' => 'Groups', 'tournament_id' => 77, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 177, 'name' => 'Knockout', 'type' => 'Knockout', 'tournament_id' => 77, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 0, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 79, 'name' => 'Groups', 'type' => 'Groups', 'tournament_id' => 79, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 179, 'name' => 'Knockout', 'type' => 'Knockout', 'tournament_id' => 79, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 80, 'name' => 'League', 'type' => 'League', 'tournament_id' => 80, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 85, 'name' => 'Groups', 'type' => 'Groups', 'tournament_id' => 85, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 185, 'name' => 'Knockout', 'type' => 'Knockout', 'tournament_id' => 85, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 88, 'name' => 'League', 'type' => 'League', 'tournament_id' => 88, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 90, 'name' => 'Groups', 'type' => 'Groups', 'tournament_id' => 90, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Total', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 190, 'name' => 'Knockout', 'type' => 'Knockout', 'tournament_id' => 90, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Total', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 91, 'name' => 'League', 'type' => 'League', 'tournament_id' => 91, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 92, 'name' => 'League', 'type' => 'League', 'tournament_id' => 92, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 93, 'name' => 'League', 'type' => 'League', 'tournament_id' => 93, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 94, 'name' => 'League', 'type' => 'League', 'tournament_id' => 94, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 95, 'name' => 'League', 'type' => 'League', 'tournament_id' => 95, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 96, 'name' => 'League', 'type' => 'League', 'tournament_id' => 96, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 97, 'name' => 'League', 'type' => 'League', 'tournament_id' => 97, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 98, 'name' => 'League', 'type' => 'League', 'tournament_id' => 98, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 99, 'name' => 'League', 'type' => 'League', 'tournament_id' => 99, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 100, 'name' => 'League', 'type' => 'League', 'tournament_id' => 100, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 101, 'name' => 'League', 'type' => 'League', 'tournament_id' => 101, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 102, 'name' => 'League', 'type' => 'League', 'tournament_id' => 102, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 103, 'name' => 'League', 'type' => 'League', 'tournament_id' => 103, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 104, 'name' => 'League', 'type' => 'League', 'tournament_id' => 104, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 105, 'name' => 'League', 'type' => 'League', 'tournament_id' => 105, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 106, 'name' => 'League', 'type' => 'League', 'tournament_id' => 106, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 107, 'name' => 'League', 'type' => 'League', 'tournament_id' => 107, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 110, 'name' => 'League', 'type' => 'League', 'tournament_id' => 110, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 111, 'name' => 'League', 'type' => 'League', 'tournament_id' => 111, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 113, 'name' => 'League', 'type' => 'League', 'tournament_id' => 113, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 114, 'name' => 'League', 'type' => 'League', 'tournament_id' => 114, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Total', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 115, 'name' => 'League', 'type' => 'League', 'tournament_id' => 115, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 116, 'name' => 'League', 'type' => 'League', 'tournament_id' => 116, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 117, 'name' => 'League', 'type' => 'League', 'tournament_id' => 117, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 118, 'name' => 'League', 'type' => 'League', 'tournament_id' => 118, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 123, 'name' => 'League', 'type' => 'League', 'tournament_id' => 123, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 124, 'name' => 'League', 'type' => 'League', 'tournament_id' => 124, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 126, 'name' => 'League', 'type' => 'League', 'tournament_id' => 126, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 127, 'name' => 'League', 'type' => 'League', 'tournament_id' => 127, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 128, 'name' => 'League', 'type' => 'League', 'tournament_id' => 128, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 0, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 129, 'name' => 'League', 'type' => 'League', 'tournament_id' => 129, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 130, 'name' => 'League', 'type' => 'League', 'tournament_id' => 130, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 131, 'name' => 'League', 'type' => 'League', 'tournament_id' => 131, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 132, 'name' => 'League', 'type' => 'League', 'tournament_id' => 132, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 133, 'name' => 'League', 'type' => 'League', 'tournament_id' => 133, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 134, 'name' => 'League', 'type' => 'League', 'tournament_id' => 134, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 135, 'name' => 'League', 'type' => 'League', 'tournament_id' => 135, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['id' => 136, 'name' => 'League', 'type' => 'League', 'tournament_id' => 136, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
            ];
        } elseif ($env === 'testing') {
            $stages = [
                ['id' => 100, 'name' => 'League', 'type' => 'League', 'tournament_id' => 100, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
            ];
        } elseif ($env === 'staging') {
            $stages = [
                ['id' => 100, 'name' => 'League', 'type' => 'League', 'tournament_id' => 100, 'points_win' => 3, 'points_draw' => 1, 'points_loss' => 0, 'no_encounters' => 1, 'ranking_criteria' => 'Direct matches', 'third_place' => 0, 'is_released' => 1, 'is_display_tbd' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at],
            ];
        } elseif ($env === 'production') {
            $stages = [];
        }

        DB::table('stages')->insert($stages);
        Schema::enableForeignKeyConstraints();
    }
}
