<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class TeamCoachSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('team_coaches')->truncate();
        $env = env('APP_ENV');
        $created_at = now();
        $updated_at = now();

        if ($env === 'development') {
            $team_coaches = [
                ['team_id' => 335, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 342, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 170, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 171, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 266, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 267, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 100, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 101, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 222, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 229, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 240, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 278, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 312, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 313, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 283, 'user_id' => 12676, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 289, 'user_id' => 12676, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 352, 'user_id' => 12871, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 353, 'user_id' => 12871, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 354, 'user_id' => 12871, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 355, 'user_id' => 12871, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 526, 'user_id' => 10020, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 527, 'user_id' => 10020, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 528, 'user_id' => 10020, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 529, 'user_id' => 10020, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 530, 'user_id' => 10020, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 531, 'user_id' => 10020, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 532, 'user_id' => 10020, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 533, 'user_id' => 10020, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 526, 'user_id' => 10156, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 527, 'user_id' => 10156, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 528, 'user_id' => 10156, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 529, 'user_id' => 10156, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 530, 'user_id' => 10156, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 531, 'user_id' => 10156, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 532, 'user_id' => 10156, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 533, 'user_id' => 10156, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 504, 'user_id' => 10622, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 505, 'user_id' => 10622, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 506, 'user_id' => 10622, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 507, 'user_id' => 10622, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 473, 'user_id' => 13005, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 474, 'user_id' => 13005, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 475, 'user_id' => 13005, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 476, 'user_id' => 13005, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 404, 'user_id' => 11181, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 405, 'user_id' => 11181, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 406, 'user_id' => 11181, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 407, 'user_id' => 11181, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 361, 'user_id' => 13006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 365, 'user_id' => 13006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 377, 'user_id' => 13006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 378, 'user_id' => 13006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 561, 'user_id' => 13007, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 562, 'user_id' => 13007, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 356, 'user_id' => 13008, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 357, 'user_id' => 13008, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 358, 'user_id' => 13008, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 359, 'user_id' => 13008, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 581, 'user_id' => 13009, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 582, 'user_id' => 13009, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 583, 'user_id' => 13009, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 352, 'user_id' => 13123, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 353, 'user_id' => 13123, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 354, 'user_id' => 13123, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 355, 'user_id' => 13123, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 872, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 873, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 874, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 880, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 861, 'user_id' => 13764, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 954, 'user_id' => 13764, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 955, 'user_id' => 13764, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1001, 'user_id' => 13008, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1002, 'user_id' => 13008, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1003, 'user_id' => 13008, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1036, 'user_id' => 13008, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1043, 'user_id' => 13008, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 972, 'user_id' => 13801, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 973, 'user_id' => 13801, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 974, 'user_id' => 13801, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1037, 'user_id' => 13801, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 932, 'user_id' => 11181, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 933, 'user_id' => 11181, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 934, 'user_id' => 11181, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 935, 'user_id' => 11181, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 989, 'user_id' => 13810, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 990, 'user_id' => 13810, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 991, 'user_id' => 13810, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 992, 'user_id' => 13810, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1041, 'user_id' => 13810, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 993, 'user_id' => 13812, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 994, 'user_id' => 13812, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 995, 'user_id' => 13812, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 996, 'user_id' => 13812, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1006, 'user_id' => 13009, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1007, 'user_id' => 13009, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1008, 'user_id' => 13009, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 887, 'user_id' => 13813, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 888, 'user_id' => 13813, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 889, 'user_id' => 13813, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1035, 'user_id' => 13813, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 861, 'user_id' => 10004, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 954, 'user_id' => 10004, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 955, 'user_id' => 10004, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 863, 'user_id' => 13814, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 984, 'user_id' => 13814, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 985, 'user_id' => 13814, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 986, 'user_id' => 13814, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 863, 'user_id' => 13815, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 984, 'user_id' => 13815, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 985, 'user_id' => 13815, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 986, 'user_id' => 13815, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 877, 'user_id' => 14112, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 878, 'user_id' => 14112, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 890, 'user_id' => 14112, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 891, 'user_id' => 14112, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 919, 'user_id' => 14112, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 920, 'user_id' => 14112, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 945, 'user_id' => 14112, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 946, 'user_id' => 14112, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 727, 'user_id' => 14112, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 754, 'user_id' => 14112, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 780, 'user_id' => 14112, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 795, 'user_id' => 14112, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 813, 'user_id' => 14112, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 822, 'user_id' => 14112, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 911, 'user_id' => 13475, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 912, 'user_id' => 13475, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 913, 'user_id' => 13475, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 877, 'user_id' => 14224, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 878, 'user_id' => 14224, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 890, 'user_id' => 14224, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 891, 'user_id' => 14224, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 919, 'user_id' => 14224, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 920, 'user_id' => 14224, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 945, 'user_id' => 14224, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 946, 'user_id' => 14224, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 727, 'user_id' => 14224, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 754, 'user_id' => 14224, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 780, 'user_id' => 14224, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 795, 'user_id' => 14224, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 813, 'user_id' => 14224, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 822, 'user_id' => 14224, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 877, 'user_id' => 14225, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 878, 'user_id' => 14225, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 890, 'user_id' => 14225, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 891, 'user_id' => 14225, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 919, 'user_id' => 14225, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 920, 'user_id' => 14225, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 945, 'user_id' => 14225, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 946, 'user_id' => 14225, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 727, 'user_id' => 14225, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 754, 'user_id' => 14225, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 780, 'user_id' => 14225, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 795, 'user_id' => 14225, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 813, 'user_id' => 14225, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 822, 'user_id' => 14225, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 877, 'user_id' => 14226, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 878, 'user_id' => 14226, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 890, 'user_id' => 14226, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 891, 'user_id' => 14226, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 919, 'user_id' => 14226, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 920, 'user_id' => 14226, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 945, 'user_id' => 14226, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 946, 'user_id' => 14226, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 727, 'user_id' => 14226, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 754, 'user_id' => 14226, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 780, 'user_id' => 14226, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 795, 'user_id' => 14226, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 813, 'user_id' => 14226, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 822, 'user_id' => 14226, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 877, 'user_id' => 14227, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 878, 'user_id' => 14227, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 890, 'user_id' => 14227, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 891, 'user_id' => 14227, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 919, 'user_id' => 14227, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 920, 'user_id' => 14227, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 945, 'user_id' => 14227, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 946, 'user_id' => 14227, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 727, 'user_id' => 14227, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 754, 'user_id' => 14227, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 780, 'user_id' => 14227, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 795, 'user_id' => 14227, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 813, 'user_id' => 14227, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 822, 'user_id' => 14227, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 877, 'user_id' => 14228, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 878, 'user_id' => 14228, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 890, 'user_id' => 14228, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 891, 'user_id' => 14228, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 919, 'user_id' => 14228, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 920, 'user_id' => 14228, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 945, 'user_id' => 14228, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 946, 'user_id' => 14228, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 727, 'user_id' => 14228, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 754, 'user_id' => 14228, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 780, 'user_id' => 14228, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 795, 'user_id' => 14228, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 813, 'user_id' => 14228, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 822, 'user_id' => 14228, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1064, 'user_id' => 13802, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1214, 'user_id' => 13802, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1215, 'user_id' => 13802, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1299, 'user_id' => 13802, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1121, 'user_id' => 13802, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1136, 'user_id' => 13802, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1143, 'user_id' => 13802, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1154, 'user_id' => 13802, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1296, 'user_id' => 13802, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1162, 'user_id' => 13802, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1080, 'user_id' => 15089, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1229, 'user_id' => 15089, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1230, 'user_id' => 15089, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1108, 'user_id' => 15089, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1186, 'user_id' => 15089, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1187, 'user_id' => 15089, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1247, 'user_id' => 15089, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1064, 'user_id' => 15090, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1214, 'user_id' => 15090, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1215, 'user_id' => 15090, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1299, 'user_id' => 15090, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1108, 'user_id' => 15090, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1186, 'user_id' => 15090, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1187, 'user_id' => 15090, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1247, 'user_id' => 15090, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1048, 'user_id' => 13604, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1095, 'user_id' => 13604, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1244, 'user_id' => 13604, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1245, 'user_id' => 13604, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1101, 'user_id' => 13475, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1236, 'user_id' => 13475, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1237, 'user_id' => 13475, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1238, 'user_id' => 13475, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1239, 'user_id' => 13475, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1260, 'user_id' => 13814, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1261, 'user_id' => 13814, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1262, 'user_id' => 13814, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1263, 'user_id' => 13814, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1087, 'user_id' => 13813, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1222, 'user_id' => 13813, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1223, 'user_id' => 13813, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1224, 'user_id' => 13813, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1127, 'user_id' => 13764, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1252, 'user_id' => 13764, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1253, 'user_id' => 13764, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1254, 'user_id' => 13764, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1257, 'user_id' => 13764, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1072, 'user_id' => 15285, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1206, 'user_id' => 15285, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1207, 'user_id' => 15285, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1208, 'user_id' => 15285, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1209, 'user_id' => 15285, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1114, 'user_id' => 11181, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1175, 'user_id' => 11181, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1176, 'user_id' => 11181, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1177, 'user_id' => 11181, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1260, 'user_id' => 13801, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1261, 'user_id' => 13801, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1262, 'user_id' => 13801, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1263, 'user_id' => 13801, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1146, 'user_id' => 15286, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1266, 'user_id' => 15286, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1267, 'user_id' => 15286, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1285, 'user_id' => 15286, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1286, 'user_id' => 15286, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1052, 'user_id' => 15287, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1191, 'user_id' => 15287, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1192, 'user_id' => 15287, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1193, 'user_id' => 15287, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1194, 'user_id' => 15287, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1156, 'user_id' => 13810, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1289, 'user_id' => 13810, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1290, 'user_id' => 13810, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1293, 'user_id' => 13810, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1294, 'user_id' => 13810, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1268, 'user_id' => 15288, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1269, 'user_id' => 15288, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1283, 'user_id' => 15288, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1270, 'user_id' => 13008, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1271, 'user_id' => 13008, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1272, 'user_id' => 13008, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1064, 'user_id' => 15313, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1214, 'user_id' => 15313, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1215, 'user_id' => 15313, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
                ['team_id' => 1299, 'user_id' => 15313, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at]
            ];
        } elseif ($env === 'testing') {
            $team_coaches = [
                ['team_id' => 872, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
            ];
        } elseif ($env === 'staging') {
            $team_coaches = [
                ['team_id' => 872, 'user_id' => 10006, 'role' => NULL, 'created_at' => $created_at, 'updated_at' => $updated_at],
            ];
        } elseif ($env === 'production') {
            $team_coaches = [];
        }

        DB::table('team_coaches')->insert($team_coaches);
        Schema::enableForeignKeyConstraints();
    }
}
